<?php

/**
 * @file
 * Contains migrate_youtube.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_youtube_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_youtube module.
    case 'help.page.migrate_youtube':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import YouTube videos through the Google API PHP Client Library') . '</p>';
      return $output;

    default:
  }
}
